name: Deploy Spring Boot to Server

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Test SSH connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: echo "Connection successful ${{ secrets.USERNAME }}"
        debug: true
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Copy jar to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "build/libs/*.jar"
        target: "/home/ubuntu/app"
        debug: true
        scp_options: -o StrictHostKeyChecking=no
        timeout: 60s

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # 현재 실행 중인 Spring Boot 애플리케이션 확인 및 중지
          PID=$(lsof -t -i:8080)
          if [ ! -z "$PID" ]; then
            echo "Stopping existing application..."
            kill $PID
          fi
          
          # 새 버전 실행
          cd /home/ubuntu/app/build/libs
          nohup java -jar -DDB_URL='${{ secrets.DB_URL }}' -DDB_USERNAME='${{ secrets.DB_USERNAME }}' -DDB_PASSWORD='${{ secrets.DB_PASSWORD }}' cicd-test-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
          echo "Application started"
